blank_issues_enabled: false
contact_links:
    - name: Help
      url: https://github.com/pishelo/pishelo-web/discussions/categories/q-a
      about: pishelo web not working as you'd expect? Not sure if it's a bug? Check the Q&A section!

    - name: Suggestions or feature request
      url: https://github.com/pishelo/pishelo-web/discussions/categories/ideas
      about: Got something you think should change or be added to pishelo web? Search for or start a new discussion about your feature request!
